name: GitHub Release
on:
  push:
    branches:
      - main
      - master
jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    steps:
      - name: Check out code repository
        uses: actions/checkout@v2
      - name: Build Docker image
        run: yarn run build
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: verify
    steps:
      - name: Check out code repository
        uses: actions/checkout@v2
      - name: Setup Node.js 12
        uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: Install dependencies
        run: yarn
      - name: Release
        env:
          GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
        run: yarn semantic-release
